name: build
on: workflow_dispatch
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - run: | 
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
          # echo "### This is a summary for spring-mvc-31-demo Project" >> $GITHUB_STEP_SUMMARY
          # echo "- Java-version 11" >> $GITHUB_STEP_WORKFLOW
          # echo "- Branch ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          # echo "- Build-version $GITHUB_RUN_NUMBER" >> $GITHUB_STEP_SUMMARY
          # echo "- Sonar false" >> $GITHUB_STEP_SUMMARY
          # echo "${{github}}"
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: installing java 11
        uses: actions/setup-java@v3
        with: 
          java-version: 11
          distribution: 'zulu'
          cache: maven
      - name: building our application
        run: mvn package -DskipTests
      - name: archiving our artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: my-app
          path: target/*.war
  Create_Release: 
     needs: build
     runs-on: ubuntu-latest
     steps: 
        - name: downloading artifact
          uses: actions/download-artifact@v3
          with: 
            name: my-app
        - name: Archive Release
          uses: thedoctor0/zip-release@0.7.5
          with:
            type: 'zip'
            filename: 'app.zip'
        - run: |
             ls
             pwd
        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env: 
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          with: 
            tag_name: v${{github.run_number}}
            release_name: Release ${{github.run_number}}
        - name: Upload Release Asset
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              asset_path: ./app.zip
              asset_name: app-${{github.run_number}}.zip
              asset_content_type: application/zip
