name: deploy
on: 
   workflow_dispatch: 
       inputs: 
          ENV: 
            type: environment
            required: true
          artifact-version: 
            type: string
            description: provide the release version
jobs: 
    Deploy: 
        runs-on: ubuntu-latest
        steps:
          - name: downloading release assets... 
            uses: dsaltares/fetch-gh-release-asset@master
            with:
              repo: 'dsaltares/godot-wild-jam-18'
              version: 'tags/v${{github.event.inputs.artifact-version}}'
              file: 'app-${{github.event.inputs.artifact-version}}.zip'
              
              token: ${{ secrets.GITHUB_TOKEN }}
             
         