name: deploy
on: 
   workflow_dispatch: 
       inputs: 
          ENV: 
            type: environment
            # required: true
          artifact-version: 
            type: string
            description: provide the release version
jobs: 
    Deploy: 
        runs-on: ubuntu-latest
        steps:
          - name: downloading release assets... 
            uses: robinraju/release-downloader@v1.9
            with: 
                repository: ${{ github.repository }}
                tag: "${{github.event.inputs.artifact-version}}"
                releaseId: "Release ${{github.event.inputs.artifact-version}}"
                fileName: "app-${{github.event.inputs.artifact-version}}.zip"
                extract: true
             
         